import './globals.css'
import { Inter } from 'next/font/google'
import Navigation from '@/component/Navigation' // el @ es para q la ruta sea mas facil y no buscar con ..
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'First Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://bootswatch.com/5/lux/bootstrap.min.css" />
     
      </head>
      
      <body className={inter.className} >
         <Navigation></Navigation>
<div className='container p-4'>

{children}
</div>
           
        </body>
    </html>
  )
}
 